name: Build LaTeX documents
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:  
          submodules: recursive
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*/*main.tex"
          glob_root_file: true
          work_in_root_file_dir: true
      - name: Publish PDFs to workflow
        uses: actions/upload-artifact@v3
        with:
          path: |
            !resources/*
            */*main.pdf

